# These settings can also be provided as environment variables, in the form, e.g.:
#    SETTING__ACTIVE_JOB_QUEUE__URL=http://...
#
# The mapping is described in `./config/initializers/config.rb`.
#

<%
  # General variables
  app_name = 'hyku'

  # Settings.solr variables
  solr_dir = 'solr/config/'
  solr_namespace = 'hydra-development'
  solr_port = ENV.fetch('SOLR_DEVELOPMENT_PORT', 8983)
  solr_url = ENV.fetch('SOLR_URL', "http://127.0.0.1:#{solr_port}/solr/#{solr_namespace}/")
%>

multitenancy:
  enabled: false
  default_host: # "%{tenant}.dev"
  admin_host:

ssl_configured: false

action_controller:
  asset_host:

redis:
  default_namespace: <%= app_name %>

solr:
  port: <%= solr_port %>
  url:  <%= solr_url %>
  cloud: true
  configset: <%= app_name %>
  configset_source_path: <%= File.join(Rails.root, solr_dir) %>
  collection:
    dir:  <%= solr_dir %>
    name: <%= solr_namespace %>
  collection_options:
    async:
    auto_add_replicas:
    collection:
      config_name: <%= app_name %>
    create_node_set:
    max_shards_per_node:
    num_shards: 1
    replication_factor:
    router:
      name:
      field:
    rule:
    shards:
    snitch:

zookeeper:
  connection_str: "localhost:9983/configs"

active_job:
  queue_adapter: :async

active_job_queue:
  url:

s3:
  upload_bucket:

fits_path: "fits.sh"

google_analytics_id:

# Register here: http://www.geonames.org/manageaccount
geonames_username: 'jcoyne'
